[package]
name = "forge"
version = "0.1.6"
edition = "2021"

[dependencies]
inquire = "0.7.5"
mlua = { version = "0.9.9", features = ["lua54"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.64"
toml = "0.8.19"
