[package]
name = "forge"
version = "0.2.2"
edition = "2021"

[dependencies]
inquire = "0.7.5"
mlua = { version = "0.9.9", features = ["lua54"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tera = "1.20.0"
thiserror = "1.0.64"
toml = "0.8.19"
walkdir = "2.5.0"
